print("\t\t................................................")
print("\t\t *****WELCOME TO HOTEL MANAGEMENT SYSYTEM*******")
print("\t\t................................................")
print("\t\t            BHAPT HOTELS WELCOMES YOU          ")
print("\t\t------------------------------------------------")
print("")
print("\t\t 1. MENU ")
print("\t\t 2. NEW CUSTOMER REGISTRATION")
print("\t\t 3. UPDATE CUSTOMER REGISTERED")
print("\t\t 4. DELETE CUSTOMER REGISTERED")
print("\t\t 5. ROOM NO. ALLOTER")
print("\t\t 6. BILL CALUCATION")
print("\t\t 7. EXIT")
print("")
print("\t\t------------------------------------------------")
