#program for showing menu screen
def menu():
    print("\t\t............................................")
    print("\t\t****WELCOME TO HOTEL MANAGEMENT SYSYTEM****")
    print("\t\t............................................")
    print("\t\t         BHAPT HOTELS WELCOMES YOU          ")
    print("")
    print("")
    print("\t*********************MAIN MENU*************************")
    print("\t     ROOM TYPE    	           COST(1 NIGHT STAY)")
    print("\t*******************************************************")
    print("\t 1 BED (NON AC)\t\t \tRs.1000/-(+500/-PER NIGHT)")
    print("\t (FOOD CHARGES EXCLUSIVE)")
    print("\t 1 BED (AC)\t\t \tRs.1300/-(+600/-PER NIGHT)")
    print("\t (FOOD CHARGES EXCLUSIVE)")	
    print("\t 1 BED (LUXURY)\t\t \tRs.2000/-(+800/-PER NIGHT)")
    print("\t (FOOD CHARGES INCLUSIVE)")
    print("\t 1 BED (DELUXE)\t\t \tRs.2500/-(+1000/-PER NIGHT)")
    print("\t (FOOD CHARGES + CLOTH WASHING INCLUSIVE)")
    print("\t ********************************************************")
    print("\t 2 BED (NON AC)\t\t \tRs.1200/-(+600/-PER NIGHT)")
    print("\t (FOOD CHARGES EXCLUSIVE)")
    print("\t 2 BED (AC)\t\t \tRs.1500/-(+750/-PER NIGHT)")
    print("\t (FOOD CHARGES EXCLUSIVE)")
    print("\t 2 BED (LUXURY)\t\t \tRs.2500/-(+1000/-PER NIGHT)")
    print("\t (FOOD CHARGES INCLUSIVE)")
    print("\t 2 BED (DELUXE)\t\t \tRs.3000/-(+1500/-PER NIGHT)")
    print("\t (FOOD CHARGES + CLOTH WASHING INCLUSIVE)")
    print("\t ********************************************************")
    print("\t 3 BED (NON AC)\t\t \tRs.1800/-(+1000/-PER NIGHT)")
    print("\t 3 BED (AC)\t\t \tRs.2500/-(+1500/-PER NIGHT)")
    print("\t ********************************************************")
    print("\t ADDITIONAL Rs.500 FOR THE FOOD CHARGES (IF INCLUDED)")
menu()
    

